name: Github Actions Demo

on: 
  push:
    branches: 
    - main
    paths-ignore: 
    - .github/**
  pull_request:
    branches: 
    - main
  schedule:
  - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: true


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output the name of the event that triggered the workflow
        run: echo ${{ github.event_name }}
      - name: Output the name of the branch that the repository is currently referencing
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v3.3.0
      - name: List all files in the repository
        run: tree
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Test
        run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Test
        run: echo "Testing..."
      - name: Really testing
        run: sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment: 
      name: production
      url: https://writeabout.net
    steps:
      - name: Step 1 deploying... 
        run: echo "Step 1 deploying... " && sleep 10
      - name: Step 2 deploying... 
        run: echo "Step 2 deploying... " && sleep 10
      - name: Step 3 deploying... 
        run: echo "Step 3 deploying... " && sleep 10
      - name: Step 4 deploying... 
        run: echo "Step 4 deploying... " && sleep 10
      - name: Step 5 deploying... 
        run: echo "Step 5 deploying... " && sleep 10
        
