name: Reuse other workflow
on: 
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Greet someone
        type: string
        required: true
        
jobs: 
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: ${{ inputs.who-to-greet }}
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: Echo time
        run: echo ${{ needs.call-workflow.outputs.current-time }}
